# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pys_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PYSWindow(object):
    def setupUi(self, PYSWindow):
        PYSWindow.setObjectName("PYSWindow")
        PYSWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(PYSWindow)
        self.centralwidget.setObjectName("centralwidget")
        PYSWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PYSWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PYSWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PYSWindow)
        self.statusbar.setObjectName("statusbar")
        PYSWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(PYSWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionSettings = QtWidgets.QAction(PYSWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PYSWindow)
        QtCore.QMetaObject.connectSlotsByName(PYSWindow)

    def retranslateUi(self, PYSWindow):
        _translate = QtCore.QCoreApplication.translate
        PYSWindow.setWindowTitle(_translate("PYSWindow", "PYS matavimai"))
        self.menuFile.setTitle(_translate("PYSWindow", "File"))
        self.menuEdit.setTitle(_translate("PYSWindow", "Edit"))
        self.actionClose.setText(_translate("PYSWindow", "Close"))
        self.actionSettings.setText(_translate("PYSWindow", "Settings ..."))
